language: rust
os:
  - linux
  - osx
rust:
  - stable
  - nightly
before_script:
  - pip2 install 'travis-cargo<0.2' --user  && export PATH=$HOME/Library/Python/2.7/bin:$HOME/.local/bin:$PATH
script:
  - travis-cargo test
  - travis-cargo build -- --manifest-path examples/drive_example/Cargo.toml
  - travis-cargo build -- --manifest-path examples/service_account/Cargo.toml
  - travis-cargo test -- --no-default-features --features no-openssl
after_success:
  - "[[ $TRAVIS_OS_NAME = linux ]] && travis-cargo --only stable coveralls"
env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
