language: rust
sudo: required
rust:
- stable
- nightly
matrix:
  include:
    - rust: stable
      # make doc-upload and coveralls work on stable only
      env: TRAVIS_RUST_VERSION=stable
    - rust: nightly
      env: FEATURE=nightly
before_script:
- pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
script:
- travis-cargo build -- --features $FEATURE --no-default-features
- travis-cargo test -- --features $FEATURE --no-default-features
- travis-cargo doc -- --features $FEATURE --no-default-features
after_success:
- travis-cargo --only stable doc-upload
- travis-cargo --only stable coveralls
env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=nightly
    - secure: Es8/QExA+XfWaTi2wQqpJL+yc4d3yU9/dfCpVFhyWpu+2XXIvbPbdqFuiZG6QVGaYOmwjlFJ5gCsAqxliG2wzVHkv+KhA1yeVn4ia41Vmx1mJlEU+O7ZNldfgjWemWKTD5kTEFtTBItswKUFH9LsFQ5sztV6/7I9kZZJAxWiXjs=
  matrix:
    - FEATURE=with_syntex
