[package]

name = "yup-oauth2"
version = "0.5.6"
authors = ["Sebastian Thiel <byronimo@gmail.com>"]
repository = "https://github.com/Byron/yup-oauth2"
description = "A partial oauth2 implementation, providing the 'device' authorization flow"
documentation = "http://byron.github.io/yup-oauth2"
keywords = ["google", "oauth", "v2"]
license = "MIT OR Apache-2.0"
build = "src/build.rs"

[dependencies]
chrono = ">= 0.2"
log = ">= 0.3"
mime = ">= 0.1"
url = "= 0.5"
hyper = ">= 0.8.0"
itertools = ">= 0.4"
serde = "0.6.0"
serde_json = "0.6.0"
serde_macros = { version = "0.6.0", optional = true }

[features]
default = ["with_syntex"]
nightly = ["serde_macros"]
with_syntex = ["serde_codegen", "syntex"]

[build-dependencies]
syntex = { version = "=0.28.0", optional = true }
serde_codegen = { version = "=0.6.13", optional = true }

[dev-dependencies]
getopts = "0.2"
open = "1.1"
yup-hyper-mock = "1.3.0"
