[package]

name = "yup-oauth2"
version = "0.3.2"
authors = ["Sebastian Thiel <byronimo@gmail.com>"]
repository = "https://github.com/Byron/yup-oauth2"
description = "A partial oauth2 implementation, providing the 'device' authorization flow"
documentation = "http://byron.github.io/yup-oauth2"
keywords = ["google", "oauth", "v2"]
license = "MIT"

[dependencies]
chrono = "*"
hyper = "*"
log = "*"
mime = "*"
url = "*"
itertools = "*"
rustc-serialize = "*"

[dev-dependencies]
getopts = "*"
yup-hyper-mock = ">= 0.1.4"
open = "*"
