[package]

name = "yup-oauth2"
version = "0.6.2"
authors = ["Sebastian Thiel <byronimo@gmail.com>", "Lewin Bormann <lbo@spheniscida.de>"]
repository = "https://github.com/Byron/yup-oauth2"
description = "A partial oauth2 implementation, providing the 'device' authorization flow"
documentation = "http://byron.github.io/yup-oauth2"
keywords = ["google", "oauth", "v2"]
license = "MIT OR Apache-2.0"
build = "src/build.rs"

[dependencies]
chrono = ">= 0.2"
log = ">= 0.3"
mime = ">= 0.1"
url = "= 0.5"
hyper = "^ 0.9.0"
itertools = ">= 0.4"
serde = "0.8"
serde_json = "0.8"
serde_macros = { version = "0.8", optional = true }

[features]
default = ["with-serde-codegen"]
nightly = ["serde_macros"]
with-serde-codegen = ["serde_codegen"]

[build-dependencies]
serde_codegen = { version = "^ 0.8", optional = true }

[dev-dependencies]
getopts = "0.2"
open = "1.1"
yup-hyper-mock = "1.3"
