[package]

name = "yup-oauth2"
version = "1.0.9"
authors = ["Sebastian Thiel <byronimo@gmail.com>", "Lewin Bormann <lbo@spheniscida.de>"]
repository = "https://github.com/dermesser/yup-oauth2"
description = "An oauth2 implementation, providing the 'device', 'service account' and 'installed' authorization flows"
documentation = "https://docs.rs/yup-oauth2/"
keywords = ["google", "oauth", "v2"]
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
base64 = "0.10"
chrono = "0.4"
hyper = "0.10.2"
hyper-native-tls = "0.3"
itertools = "0.8"
log = "0.3"
openssl = {version = "0.10", optional = true}
rustls = {version = "0.14", optional = true}
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
url = "1"

[features]
default = ["openssl"]
no-openssl = ["rustls"]

[dev-dependencies]
getopts = "0.2"
open = "1.1"
yup-hyper-mock = "2.0"
