[package]

name = "yup-oauth2"
version = "6.2.0"
authors = ["Sebastian Thiel <byronimo@gmail.com>", "Lewin Bormann <lbo@spheniscida.de>"]
repository = "https://github.com/dermesser/yup-oauth2"
description = "An oauth2 implementation, providing the 'device', 'service account' and 'installed' authorization flows"
documentation = "https://docs.rs/yup-oauth2/"
keywords = ["google", "oauth", "v2"]
license = "MIT OR Apache-2.0"
edition = "2018"

[[example]]
name = "custom_flow"
required-features = ["hyper-rustls"]

[[example]]
name = "custom_storage"
required-features = ["hyper-rustls"]

[[test]]
name = "tests"
required-features = ["hyper-rustls"]

[features]
default = ["hyper-rustls"]

[dependencies]
base64 = "0.13.0"
chrono = { version = "0.4", features = ["serde"] }
http = "0.2"
hyper = { version = "0.14", features = ["client", "server", "tcp", "http2"] }
hyper-rustls = { version = "0.22.1", optional = true }
hyper-tls = { version = "0.5.0", optional = true }
log = "0.4"
rustls = "0.19"
seahash = "4"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
tokio = { version = "1.0", features = ["fs", "macros", "io-std", "io-util", "time", "sync", "rt"] }
url = "2"
percent-encoding = "2"
futures = "0.3"
async-trait = "^0.1"
anyhow = "1.0.38"
itertools = "0.10.0"

[dev-dependencies]
httptest = "0.14"
env_logger = "0.7"
tempfile = "3.1"
webbrowser = "0.5"
hyper-rustls = "0.22.1"

[workspace]
members = ["examples/test-installed/", "examples/test-svc-acct/", "examples/test-device/", "examples/service_account", "examples/drive_example", "examples/test-adc"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "yup_oauth2_docsrs"]
