[package]

name = "yup-oauth2"
version = "3.0.4"
authors = ["Sebastian Thiel <byronimo@gmail.com>", "Lewin Bormann <lbo@spheniscida.de>"]
repository = "https://github.com/dermesser/yup-oauth2"
description = "An oauth2 implementation, providing the 'device', 'service account' and 'installed' authorization flows"
documentation = "https://docs.rs/yup-oauth2/"
keywords = ["google", "oauth", "v2"]
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
base64 = "0.10"
chrono = "0.4"
http = "0.1"
hyper = {version = "0.12", default-features = false}
hyper-rustls = "0.16"
itertools = "0.8"
log = "0.3"
rustls = "0.15"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
url = "1"
futures = "0.1"
tokio-threadpool = "0.1"
tokio = "0.1"
tokio-timer = "0.2"

[dev-dependencies]
getopts = "0.2"
open = "1.1"
yup-hyper-mock = "3.14"
mockito = "0.17"
env_logger = "0.6"

[workspace]
members = ["examples/test-installed/", "examples/test-svc-acct/", "examples/test-device/"]
