[package]
name = "drive_example"
version = "0.1.0"
authors = ["Lewin Bormann <lbo@spheniscida.de>"]

[dependencies]
yup-oauth2 = "^ 1.0"
google-drive3 = "^ 1.0"
hyper = "^ 0.10"
hyper-rustls = "0.6.1"
