[package]
name = "drive_example"
version = "0.1.0"
authors = ["Lewin Bormann <lbo@spheniscida.de>"]
edition = "2018"

[dependencies]
yup-oauth2 = "^ 1.0"
google-drive3 = "^ 1.0"
hyper = "^ 0.10"
hyper-native-tls = "0.2"
